import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { isAxiosError } from 'axios'
import { FileText } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { deleteQuote, downloadQuotePdf, fetchQuotes, patchQuote, type QuoteListItem } from '@/api/quotes'
import { EmptyState } from '@/components/EmptyState'
import { Skeleton } from '@/components/Skeleton'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { useAuthStore } from '@/store/authStore'

function formatInrPlain(n: number) {
  return new Intl.NumberFormat('en-IN', { maximumFractionDigits: 0 }).format(n)
}

function formatInr(n: number) {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n)
}

function vehicleTypeLong(raw: string) {
  const m: Record<string, string> = {
    TWO_W: '2-Wheeler',
    FOUR_W: '4-Wheeler',
    COMMERCIAL: 'Commercial',
    EV: 'EV',
  }
  return m[raw] ?? raw
}

function quoteWhatsAppText(row: QuoteListItem, businessName: string) {
  return `Fee Quote — ${vehicleTypeLong(row.vehicleTypeRaw)} in ${row.state}
Invoice Price: ₹${formatInrPlain(row.invoicePrice)}
Road Tax: ₹${formatInrPlain(row.totalTax)}
Registration: ₹${formatInrPlain(row.totalFees)}
TOTAL PAYABLE: ₹${formatInrPlain(row.grandTotal)}
Generated by ${businessName}`
}

export function QuotesPage() {
  const queryClient = useQueryClient()
  const businessName = useAuthStore((s) => s.businessName) ?? 'Your business'
  const [page, setPage] = useState(1)
  const pageSize = 10
  const [pendingDeleteId, setPendingDeleteId] = useState<string | null>(null)

  const listQuery = useQuery({
    queryKey: ['quotes', page, pageSize],
    queryFn: () => fetchQuotes({ page, pageSize }),
  })

  const deleteMut = useMutation({
    mutationFn: (id: string) => deleteQuote(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['quotes'] }),
  })

  const markSentMut = useMutation({
    mutationFn: (id: string) => patchQuote(id, { sentViaWhatsapp: true }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['quotes'] }),
  })

  const download = async (id: string) => {
    const blob = await downloadQuotePdf(id)
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `quote-${id}.pdf`
    a.click()
    URL.revokeObjectURL(url)
  }

  const sendWhatsApp = (row: QuoteListItem) => {
    const text = quoteWhatsAppText(row, businessName)
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer')
    markSentMut.mutate(row.id)
  }

  const total = listQuery.data?.total ?? 0
  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-text-primary">Quotes</h1>
        <p className="mt-1 text-sm text-text-secondary">Fee quotes linked to saved calculations.</p>
      </div>

      <div className="overflow-x-auto rounded-lg border border-border-card bg-bg-card">
        <table className="w-full min-w-[900px] text-left text-sm">
          <thead className="border-b border-border-card bg-bg-app text-xs font-medium uppercase text-text-secondary">
            <tr>
              <th className="px-3 py-3">Client</th>
              <th className="px-3 py-3">Vehicle type</th>
              <th className="px-3 py-3">State</th>
              <th className="px-3 py-3">Invoice</th>
              <th className="px-3 py-3">Total fees</th>
              <th className="px-3 py-3">Date</th>
              <th className="px-3 py-3">Sent?</th>
              <th className="px-3 py-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border-card">
            {listQuery.isLoading ? (
              <tr>
                <td colSpan={8} className="px-3 py-8 text-center text-text-secondary">
                  <div className="space-y-2 p-2">
                    {Array.from({ length: 5 }).map((_, i) => (
                      <Skeleton key={i} className="h-9 w-full" />
                    ))}
                  </div>
                </td>
              </tr>
            ) : listQuery.isError ? (
              <tr>
                <td colSpan={8} className="px-3 py-8 text-center text-accent-red">
                  {isAxiosError(listQuery.error)
                    ? String((listQuery.error.response?.data as { message?: string })?.message)
                    : 'Failed to load quotes'}
                </td>
              </tr>
            ) : !listQuery.data?.items.length ? (
              <tr>
                <td colSpan={8} className="px-3 py-8 text-center text-text-secondary">
                  <EmptyState
                    icon={<FileText className="h-16 w-16" strokeWidth={1.2} />}
                    title="No quotes yet"
                    description="Create fee outputs in the calculator and save quotes for clients."
                    action={
                      <Button asChild type="button">
                        <Link to="/calculator">Open Calculator</Link>
                      </Button>
                    }
                  />
                </td>
              </tr>
            ) : (
              listQuery.data.items.map((row) => (
                <tr key={row.id}>
                  <td className="px-3 py-2 font-medium text-text-primary">{row.clientName}</td>
                  <td className="px-3 py-2 text-text-secondary">{row.vehicleType}</td>
                  <td className="px-3 py-2 text-text-secondary">{row.state}</td>
                  <td className="px-3 py-2 tabular-nums text-text-primary">{formatInr(row.invoicePrice)}</td>
                  <td className="px-3 py-2 tabular-nums text-text-primary">{formatInr(row.totalFees)}</td>
                  <td className="px-3 py-2 tabular-nums text-text-secondary">
                    {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(
                      new Date(row.date),
                    )}
                  </td>
                  <td className="px-3 py-2">
                    {row.sentViaWhatsapp ? (
                      <span className="inline-flex rounded-full bg-accent-green/15 px-2 py-0.5 text-xs font-medium text-accent-green">
                        Yes
                      </span>
                    ) : (
                      <span className="inline-flex rounded-full bg-bg-app px-2 py-0.5 text-xs text-text-secondary">
                        No
                      </span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-right">
                    <div className="flex flex-wrap justify-end gap-1">
                      <Button type="button" variant="outline" size="sm" onClick={() => void download(row.id)}>
                        Download PDF
                      </Button>
                      <Button type="button" variant="outline" size="sm" onClick={() => sendWhatsApp(row)}>
                        Send WhatsApp
                      </Button>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        className="text-accent-red hover:bg-accent-red/10"
                        disabled={deleteMut.isPending}
                        onClick={() => setPendingDeleteId(row.id)}
                      >
                        Delete
                      </Button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {totalPages > 1 ? (
        <div className="flex items-center justify-between text-sm">
          <Button type="button" variant="outline" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>
            Previous
          </Button>
          <span className="text-text-secondary">
            Page {page} of {totalPages}
          </span>
          <Button type="button" variant="outline" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>
            Next
          </Button>
        </div>
      ) : null}

      <AlertDialog open={Boolean(pendingDeleteId)} onOpenChange={(open) => !open && setPendingDeleteId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete quote?</AlertDialogTitle>
            <AlertDialogDescription>This action cannot be undone.</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => pendingDeleteId && deleteMut.mutate(pendingDeleteId)}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
